repos:
  - repo: https://github.com/facebook/pyrefly
    rev: main
    hooks:
      - id: pyrefly-typecheck
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [ --fix ]
      - id: ruff-format
        types_or: [python, pyi, jupyter]
